spring:
  application:
    name: plugin-test
  redis:
    database: 14
    host: localhost
    port: 6379

server:
  port: 9024
delay-queue:
  center-url: http://localhost:9023
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 25   #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除(默认90秒)
    lease-renewal-interval-in-seconds: 7       #服务刷新时间配置，每隔这个时间会主动心跳一次(默认30秒)
  client:
    service-url:
      defaultZone: http://localhost:2313/eureka
    registry-fetch-interval-seconds: 10  #重新刷新服务地址的时间